language: rust
cache: cargo

addons:
    apt:
        packages:
            - gcc-arm-linux-gnueabihf
            - libc6-dev-armhf-cross

rust:
    - stable
    - beta
    - nightly

install:
    - git clone https://github.com/raspberrypi/tools.git --depth=1 /tmp/rpi-tools
    - mkdir .cargo
    - cp .ci/cargo-config .cargo/config
    - rustup target add arm-unknown-linux-gnueabihf
    - rustup target add armv7-unknown-linux-gnueabihf

script:
    - cargo build --verbose --target $TARGET --lib --examples
    - cargo build --verbose --target $TARGET --lib --release

env:
    - TARGET=arm-unknown-linux-gnueabihf
    - TARGET=armv7-unknown-linux-gnueabihf

jobs:
    allow_failures:
        - rust: nightly
